REMOVED_FILE_LIST = "\
usr/bin/CcspMtaAgentSsp \
usr/lib/libmta_tr181.so* \
usr/ccsp/mta \
usr/bin/CcspEPONAgentSsp \
usr/lib/libepon_tr181.so* \
usr/ccsp/epon \
usr/lib/python* \
usr/bin/GponManager \
usr/rdk/gponmanager \
usr/bin/xdslmanager \
usr/rdk/xdslmanager \
etc/rdk/conf/xdsl_manager_conf.json \
etc/rdk/conf/gpon_manager_conf.json \
etc/rdk/schemas/xdsl_hal_schema.json \
etc/rdk/schemas/gpon_hal_schema.json \
"
